name: 'airbnb'
version: '1.0.0'

profile: 'airbnb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  airbnb:
    +materialized: view
    dim:
      +materialized: table
    src:
      +materialized: ephemeral

# Storing test failure results in the data warehouse schema __test_results. This is useful for debugging test failures.
tests:
  airbnb:
    +store_failures: true
    +schema: __test_results